#!/usr/bin/env bash
#
# nexais installer — sets up a virtualenv, installs nexais, and creates a short
# launcher command on your PATH.
#
# Usage:
#   ./install.sh                 # installs command "nexai" into ~/.local/bin
#   ./install.sh myai            # name the command "myai" instead
#   ./install.sh nexai --bin /usr/local/bin
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$SCRIPT_DIR"

CMD_NAME="nexai"
BIN_DIR="${NEXAI_BIN:-$HOME/.local/bin}"

while [ $# -gt 0 ]; do
  case "$1" in
    --bin)   BIN_DIR="$2"; shift 2 ;;
    --bin=*) BIN_DIR="${1#*=}"; shift ;;
    -h|--help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//; 1d'
      exit 0 ;;
    -*) echo "Unknown option: $1" >&2; exit 2 ;;
    *)  CMD_NAME="$1"; shift ;;
  esac
done

info() { printf '\033[36m•\033[0m %s\n' "$*"; }
ok()   { printf '\033[32m✓\033[0m %s\n' "$*"; }
warn() { printf '\033[33m!\033[0m %s\n' "$*"; }

# --- find a Python 3.10+ interpreter ----------------------------------------
find_python() {
  for c in python3.13 python3.12 python3.11 python3.10 python3 python; do
    if command -v "$c" >/dev/null 2>&1 &&
       "$c" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)' 2>/dev/null; then
      command -v "$c"
      return 0
    fi
  done
  return 1
}

if ! PY="$(find_python)"; then
  echo "Error: nexais needs Python 3.10 or newer, but none was found." >&2
  echo "Install one (e.g. 'brew install python@3.13') and re-run." >&2
  exit 1
fi
info "Python: $PY ($("$PY" --version 2>&1))"

# --- create/refresh the virtualenv ------------------------------------------
VENV="$REPO/.venv"
if [ ! -x "$VENV/bin/python" ]; then
  info "Creating virtualenv at $VENV"
  "$PY" -m venv "$VENV"
else
  info "Reusing virtualenv at $VENV"
fi

info "Installing nexais and dependencies…"
"$VENV/bin/python" -m pip install --quiet --upgrade pip
"$VENV/bin/pip" install --quiet -e "$REPO"
ok "nexais installed ($("$VENV/bin/nexais" --version))"

# --- write the launcher -----------------------------------------------------
mkdir -p "$BIN_DIR"
LAUNCHER="$BIN_DIR/$CMD_NAME"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# nexais launcher (generated by install.sh)
exec "$VENV/bin/nexais" "\$@"
EOF
chmod +x "$LAUNCHER"
ok "Created command '$CMD_NAME' → $LAUNCHER"

# --- PATH check -------------------------------------------------------------
case ":$PATH:" in
  *":$BIN_DIR:"*)
    ok "$BIN_DIR is on your PATH."
    echo
    ok "All set. Run:  $CMD_NAME"
    ;;
  *)
    warn "$BIN_DIR is not on your PATH yet."
    echo "   Add this line to your ~/.zshrc (or ~/.bashrc):"
    echo "     export PATH=\"$BIN_DIR:\$PATH\""
    echo "   Then open a new terminal, or run:  export PATH=\"$BIN_DIR:\$PATH\""
    echo
    ok "Until then you can run it directly:  $LAUNCHER"
    ;;
esac
